---

- name: shutdown services, sockets and timers
  ansible.builtin.service:
    name: "{{ item }}"
    state: "{{ snapd_state }}"
    enabled: "{{ snapd_enabled }}"
  failed_when: false
  loop:
    "{{ snapd_services }}"

- name: purge all these bullshit
  when:
    - snapd_purge
  block:
    - name: debian based
      when:
        - ansible_os_family | lower == 'debian'
      block:

        - name: make sure python3-apt is installed
          ansible.builtin.package:
            name:
              - python3-apt
            state: present

        - name: remove snapd packages (debian)
          ansible.builtin.package:
            name: "{{ snapd_block_packages }}"
            state: absent
            purge: true

        - name: block installation
          when:
            - snapd_block_packages is defined
            - snapd_block_packages | count > 0
          block:
            - name: block later installations of snapd
              ansible.builtin.template:
                src: apt/preferences.d/snapd.pref.j2
                dest: /etc/apt/preferences.d/snapd.pref
                mode: 0644
              when:
                - snapd_block_later_installation

            - name: clean apt cache
              ansible.builtin.command: |
                apt-get clean
              register: apt_clean
              changed_when: apt_clean.rc != 0
              failed_when: apt_clean.rc != 0

            - name: update package cache
              ansible.builtin.package:
                update_cache: true

    - name: remove snapd packages (other)
      ansible.builtin.package:
        name: "{{ snapd_block_packages }}"
        state: absent
      when:
        - ansible_os_family | lower != 'debian'

    - name: remove snapd-related directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ snapd_files }}"
      loop_control:
        label: "{{ item }}"

...
